language: node_js
node_js:
- '5'
addons:
  code_climate:
    repo_token: "23edf7695eb19ab4c9f74a317fef371d61cf1391a62ebd157a7b8b5d79b0c384"
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: KzvA82OOkLX7tajo4EsK21KVjqvrTBKM2TK0Q29ZHRJ7FAIP9hcicRkULvcuCrTONepVTlli9fsYDYs7Jha+r1VOld54Y5u4UHdxLpVX8LwRKXpcaYPdI+hydad6Qc5/RJdW6gtonG9iDI5wtkp641IYz9KoeaoGAlMvFJnIjB3kD0wySBFDTMOUstoRm+Djc9ZHwNgCrNWP5Jn3MXDTrr/q9HuSZgNAXQ4//Yf7B2kM20QSEob4LhjSxqGX5yG3/wnNCOIJeIwOhzMrNbZDRr08un8bMLLXoCOr7V1kSLt2LDmsrBUWl54UxHyqlW+ra2o/rA+ukSmm0Dne54PLzsU0nrOADYrzwVu3B/MU3uZOdpF5/H+xgpfexhFNSeYen69CFPj2qLZ2L1wqLzgoc4nCrgI90REMAdc+aXEXfD27Z8eSdUQHuDfaMaCTg83NKcgE7Kb9fjuIDS9jZmnGKniocSCTxUklFm3/Cz1olczJ2SjnQXoNgfTvW3Q8wxdYRvcFCLM+dNm3juZsTEcRG7zT9i1hccT72zhYzKL06LtzF0ofj9O3ZwIrCjKwq8pKibQaJCaPo7lsbutdvfpKtceHLnjijvBMcpmqpSVdP2OmWl+6NgOHWk9cYiQjOZhVBrKqzr9Y7F0BmPPndZRhIIZj+FuWKXk9lqAlbl4r5SA=
  on:
    tags: true
    branches: true
