language: cpp
os:
- linux
- osx
env:
  matrix:
  - PACKAGER_NODE_VERSION="0.10" PACKAGER_ARCH="amd64"
  - PACKAGER_NODE_VERSION="0.10" PACKAGER_ARCH="386"
  - PACKAGER_NODE_VERSION="0.12" PACKAGER_ARCH="amd64"
  - PACKAGER_NODE_VERSION="0.12" PACKAGER_ARCH="386"
  - PACKAGER_NODE_VERSION="4" PACKAGER_ARCH="amd64"
  - PACKAGER_NODE_VERSION="4" PACKAGER_ARCH="386"
  - PACKAGER_NODE_VERSION="5.5" PACKAGER_ARCH="amd64" MAIN_BUILD=true
  - PACKAGER_NODE_VERSION="5.5" PACKAGER_ARCH="386"
matrix:
  exclude:
  - os: osx
    env: PACKAGER_NODE_VERSION="0.10" PACKAGER_ARCH="386"
  - os: osx
    env: PACKAGER_NODE_VERSION="0.12" PACKAGER_ARCH="386"
  - os: osx
    env: PACKAGER_NODE_VERSION="4" PACKAGER_ARCH="386"
  - os: osx
    env: PACKAGER_NODE_VERSION="5.5" PACKAGER_ARCH="386"
before_install:
- curl -fsS "https://meshblu-connector.octoblu.com/tools/packager/v6.0.1/travis_install_node.sh" | bash
install:
- npm install
script:
- npm test
before_deploy:
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PACKAGER_OS="darwin" fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then export PACKAGER_OS="linux" fi
- if [ "$TRAVIS_OS_NAME" == "linux" && "$MAIN_BUILD" == "true" ]; then export NPM_PUBLISH=true fi
- export PACKAGER_CONNECTOR="run-legacy"
- export PACKAGER_TAG="$TRAVIS_TAG"
- curl -fsS "https://meshblu-connector.octoblu.com/tools/packager/v6.0.1/build.sh" | bash
deploy:
- provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key:
    secure: "jRow0QUPx7XFcp1ZcjDUagzQVHxreAAUPEjS0UqCVCdzEkgsC+sZ2N3cybwvrPtXtZ2i+oUDQ4F/8w1AOXMTMgkZuo9qmMO9xzY6ov215LflcBp+Waxyi5CYfqeglQKvcra4NftHPhZBbhrghtfzpFO7Lhe7A3UUSNoqbr27JC7hdj0osyC90H4gXJiueAeYobNv6Ulhtj1Et4LnlmUkY34Ez9fw3arh+q8CG/WL7xkqNtcBZMYVf86A9HIXKfkV7/eHF25mo0+ief0pv/DjYhLp3H5ch+ql2uxnfbIUbV/4Unbh93V8JP9Mp/7jtTLHtHXAAs9ty1+CJq7AKjovlwQsRwt6xQVeufLEUMY5fwatIbDDFXFMrOIXNFpO2G8AhgstJmn6GC9kit1Wj6tQm/ME6YchRbqrPYS0SKRTUqrfBo9UjDJHaXmXmDQMfXSd5d2yGcEux/WfTQTofqwPWOEl99aJPJNNa+sg8QRZs9TCL+Vez0UmZHRIHTQiuZ4FuZ8w4mzKsH89juUFW1UiN5bDJrlqc6f9birF0UjN24iY/3fQVOkbopuZOrXX79PJ3V3wkzCfhvDvDo9JNvem4digs1cgS8DbDuV42sT9mzxZ0NkAp8hQYbP11kyE2m1qSbXNpxT9QYUfC1cbmHTP+DMI4goyBlYdYtarjmuyBIQ="
  bucket: meshblu-connector
  local-dir: deploy
  upload-dir: connectors
  region: us-west-2
  skip_cleanup: true
  on:
    tags: true
- provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: KzvA82OOkLX7tajo4EsK21KVjqvrTBKM2TK0Q29ZHRJ7FAIP9hcicRkULvcuCrTONepVTlli9fsYDYs7Jha+r1VOld54Y5u4UHdxLpVX8LwRKXpcaYPdI+hydad6Qc5/RJdW6gtonG9iDI5wtkp641IYz9KoeaoGAlMvFJnIjB3kD0wySBFDTMOUstoRm+Djc9ZHwNgCrNWP5Jn3MXDTrr/q9HuSZgNAXQ4//Yf7B2kM20QSEob4LhjSxqGX5yG3/wnNCOIJeIwOhzMrNbZDRr08un8bMLLXoCOr7V1kSLt2LDmsrBUWl54UxHyqlW+ra2o/rA+ukSmm0Dne54PLzsU0nrOADYrzwVu3B/MU3uZOdpF5/H+xgpfexhFNSeYen69CFPj2qLZ2L1wqLzgoc4nCrgI90REMAdc+aXEXfD27Z8eSdUQHuDfaMaCTg83NKcgE7Kb9fjuIDS9jZmnGKniocSCTxUklFm3/Cz1olczJ2SjnQXoNgfTvW3Q8wxdYRvcFCLM+dNm3juZsTEcRG7zT9i1hccT72zhYzKL06LtzF0ofj9O3ZwIrCjKwq8pKibQaJCaPo7lsbutdvfpKtceHLnjijvBMcpmqpSVdP2OmWl+6NgOHWk9cYiQjOZhVBrKqzr9Y7F0BmPPndZRhIIZj+FuWKXk9lqAlbl4r5SA=
  on:
    tags: true
    condition: "$NPM_PUBLISH=true"
